/**
 * Copyright (C) Key Bridge Global LLC and/or its affiliates.
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * <p/>
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.whitespace_db_providers._2011.interdb.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-2b01 Generated
 * source version: 2.2
 * <p/>
 * This is an interface for the Soap Service implementation.
 * <p/>
 * @author Jesse Caulfield
 */
@WebService(name = "WSpaces_WS_PT", targetNamespace = "http://www.whitespace-db-providers.org/2011//InterDB/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
  ObjectFactory.class
})
public interface WSpacesWSPT {

  /**
   *
   * @param parameters
   * @return returns
   *         org.whitespace_db_providers._2011.interdb.ws.RealTimePollResponse
   */
  @WebMethod(operationName = "RealTimePoll", action = "http://www.whitespace-db-providers.org/2011//InterDB/ws/RealTimePoll")
  @WebResult(name = "RealTimePollResponse", targetNamespace = "http://www.whitespace-db-providers.org/2011//InterDB/ws", partName = "parameters")
  public RealTimePollResponse realTimePoll(@WebParam(name = "RealTimePollRequest", targetNamespace = "http://www.whitespace-db-providers.org/2011//InterDB/ws", partName = "parameters") RealTimePollRequest parameters);
}
